name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup SSH Key
      env:
        EC2_PEM_KEY: ${{ secrets.EC2_PEM_KEY }}
      run: |
        # Save the private key to a file and set permissions
        echo "$EC2_PEM_KEY" > ec2-key.pem
        chmod 400 ec2-key.pem

    - name: Deploy to EC2 with Git Pull
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
        REPO_URL: ${{ secrets.REPO_URL }}
      run: |
        ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
          # Navigate to the web directory or clone if it doesn't exist
          if [ ! -d "/var/www/html/NLP-SCE" ]; then
            sudo git clone ${{ secrets.REPO_URL }} /var/www/html/NLP-SCE
          else
            cd /var/www/html/NLP-SCE
            sudo git pull origin main  # or your branch
          fi
          
          # Restart Nginx
          sudo systemctl restart nginx
        EOF
